gradle: Package missing files (#6255)
Fixes:

    org.gradle.api.internal.classpath.UnknownModuleException: Cannot find module 'ant' in distribution directory 'C:\msys64\usr\share\java\gradle'.